/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package métododelredondeo;

/**
 *
 * @author lab02
 */
public class Redonde extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    public Redonde() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_num1 = new javax.swing.JLabel();
        lbl_num2 = new javax.swing.JLabel();
        txt_num1 = new javax.swing.JTextField();
        txt_num2 = new javax.swing.JTextField();
        txt_x1 = new javax.swing.JTextField();
        btn_sumar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        lbl_num3 = new javax.swing.JLabel();
        lbl_num4 = new javax.swing.JLabel();
        txt_num3 = new javax.swing.JTextField();
        txt_num4 = new javax.swing.JTextField();
        txt_x2 = new javax.swing.JTextField();
        txt_x3 = new javax.swing.JTextField();
        txt_x4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_num5 = new javax.swing.JLabel();
        lbl_num6 = new javax.swing.JLabel();
        lbl_num7 = new javax.swing.JLabel();
        lbl_num8 = new javax.swing.JLabel();
        xx1 = new javax.swing.JTextField();
        xx2 = new javax.swing.JTextField();
        xx3 = new javax.swing.JTextField();
        xx4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ztext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Redondeo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(0, 0, 255));
        lbl_Titulo.setText("MÉTODO DEL REDONDEO");

        lbl_num1.setText("X1");

        lbl_num2.setText("X2");

        txt_num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num1ActionPerformed(evt);
            }
        });

        txt_num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num2ActionPerformed(evt);
            }
        });

        txt_x1.setEditable(false);
        txt_x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_x1ActionPerformed(evt);
            }
        });

        btn_sumar.setText("Redondeo");
        btn_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        lbl_num3.setText("X3");

        lbl_num4.setText("X4");

        txt_num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num3ActionPerformed(evt);
            }
        });

        txt_num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num4ActionPerformed(evt);
            }
        });

        txt_x2.setEditable(false);
        txt_x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_x2ActionPerformed(evt);
            }
        });

        txt_x3.setEditable(false);
        txt_x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_x3ActionPerformed(evt);
            }
        });

        txt_x4.setEditable(false);
        txt_x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_x4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Z=");

        lbl_num5.setText("X1*");

        lbl_num6.setText("+ X2*");

        lbl_num7.setText("+X3*");

        lbl_num8.setText("+X4*");

        jLabel2.setText("Z=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_num5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xx1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_num6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xx2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_num7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xx3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_num8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xx4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 30, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_num2)
                                    .addComponent(lbl_num1)
                                    .addComponent(lbl_num3)
                                    .addComponent(lbl_num4))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_num2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_num1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_num3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(txt_num4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_x1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_x3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_x4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_sumar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_limpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ztext, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addGap(110, 110, 110)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_Titulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_num1)
                    .addComponent(txt_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_num2)
                    .addComponent(txt_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_num3)
                    .addComponent(txt_num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_num4)
                    .addComponent(txt_num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_num5)
                    .addComponent(lbl_num6)
                    .addComponent(lbl_num7)
                    .addComponent(lbl_num8)
                    .addComponent(xx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ztext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sumar)
                    .addComponent(btn_limpiar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num1ActionPerformed

    private void btn_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarActionPerformed
        //declaro variables
        double num1, num2,num3, num4;
        double n1,n2,n3,n4,z;
        double nn1,nn2,nn3,nn4;
        double x1,x2,x3,x4;
        //asigno valores
        num1= Double.parseDouble(txt_num1.getText());
        num2= Double.parseDouble(txt_num2.getText());
        num3= Double.parseDouble(txt_num3.getText());
        num4= Double.parseDouble(txt_num4.getText());
        //Operaciones
        x1=(num1*100000-(num1*100000)%100000)/100000;
        x2=(num2*100000-(num2*100000)%100000)/100000;
        x3=(num3*100000-(num3*100000)%100000)/100000;
        x4=(num4*100000-(num4*100000)%100000)/100000;
        //mostrar el resultado
        txt_x1.setText(String.valueOf(x1)); 
        txt_x2.setText(String.valueOf(x2));
        txt_x3.setText(String.valueOf(x3));
        txt_x4.setText(String.valueOf(x4));
        
        n1=Double.parseDouble(txt_x1.getText());
        n2=Double.parseDouble(txt_x2.getText());
        n3=Double.parseDouble(txt_x3.getText());
        n4=Double.parseDouble(txt_x4.getText());
        
        nn1=Double.parseDouble(xx1.getText());
        nn2=Double.parseDouble(xx2.getText());
        nn3=Double.parseDouble(xx3.getText());
        nn4=Double.parseDouble(xx4.getText());
        
        z=nn1*n1+nn2*n2+nn3*n3+nn4*n4;
        
        ztext.setText(String.valueOf(z));
        
        
        
    }//GEN-LAST:event_btn_sumarActionPerformed

    private void txt_x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_x1ActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_num1.setText("");
        txt_num2.setText("");
        txt_num3.setText("");
        txt_num4.setText("");
        txt_x1.setText("");
        txt_x2.setText("");
        txt_x3.setText("");
        txt_x4.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num2ActionPerformed

    private void txt_num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num3ActionPerformed

    private void txt_num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num4ActionPerformed

    private void txt_x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_x2ActionPerformed

    private void txt_x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_x3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_x3ActionPerformed

    private void txt_x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_x4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_x4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Redonde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Redonde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Redonde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Redonde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Redonde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_sumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_num1;
    private javax.swing.JLabel lbl_num2;
    private javax.swing.JLabel lbl_num3;
    private javax.swing.JLabel lbl_num4;
    private javax.swing.JLabel lbl_num5;
    private javax.swing.JLabel lbl_num6;
    private javax.swing.JLabel lbl_num7;
    private javax.swing.JLabel lbl_num8;
    private javax.swing.JTextField txt_num1;
    private javax.swing.JTextField txt_num2;
    private javax.swing.JTextField txt_num3;
    private javax.swing.JTextField txt_num4;
    private javax.swing.JTextField txt_x1;
    private javax.swing.JTextField txt_x2;
    private javax.swing.JTextField txt_x3;
    private javax.swing.JTextField txt_x4;
    private javax.swing.JTextField xx1;
    private javax.swing.JTextField xx2;
    private javax.swing.JTextField xx3;
    private javax.swing.JTextField xx4;
    private javax.swing.JTextField ztext;
    // End of variables declaration//GEN-END:variables
}
